# ===========================================
# DOCKER COMPOSE - PRODUCTION
# ===========================================
# Configuration optimisée pour la production
# - Chargement automatique de .env.production
# - Build optimisé avec multi-stage
# - Healthchecks robustes
# - Logs limités avec rotation
# - Variables d'environnement sécurisées

# IMPORTANT: Créer un fichier .env.production à la racine avec:
# - POSTGRES_PASSWORD
# - SECRET_KEY
# - ALLOWED_ORIGINS
# - NEXT_PUBLIC_API_URL

# --- Réseau ---
networks:
  crm-network:
    driver: bridge

# --- Volumes ---
volumes:
  postgres-data:
    driver: local
  api-uploads:
    driver: local
  api-backups:
    driver: local

# --- Services ---
services:

  # ========================================
  # POSTGRES
  # ========================================
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crm_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD doit être défini dans .env.production}
      POSTGRES_DB: ${POSTGRES_DB:-crm_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "max_connections=50"
    ports:
      # Utiliser un port différent pour éviter les conflits avec PostgreSQL local
      - "127.0.0.1:${POSTGRES_EXTERNAL_PORT:-5433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request;urllib.request.urlopen(\"http://localhost:8000/api/v1/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ========================================
  # API (FastAPI)
  # ========================================
  api:
    build:
      context: ./crm-backend
      dockerfile: Dockerfile
      target: production
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    # Charger les variables depuis le fichier d'env (configurable via COMPOSE_ENV_FILE, défaut .env.production)
    env_file:
      - ${COMPOSE_ENV_FILE:-.env.production}
    environment:
      # URL de connexion PostgreSQL (utilise le nom du service 'postgres')
      DATABASE_URL: postgresql://${POSTGRES_USER:-crm_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-crm_db}
      # Sécurité
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY:?SECRET_KEY doit être défini dans .env.production}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-["https://crm.alforis.fr"]}
      # JWT
      JWT_ALGORITHM: ${JWT_ALGORITHM:-HS256}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS:-24}
      # Environnement
      ENVIRONMENT: production
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-10}
      API_PORT: 8000
    working_dir: /app
    # Production: 4 workers, pas de logs d'accès pour les perfs
    command: uvicorn main:app --host 0.0.0.0 --port ${API_PORT:-8000} --proxy-headers
    ports:
      - "127.0.0.1:${API_PORT:-8000}:8000"
    volumes:
      - api-uploads:/app/uploads
      - api-backups:/app/backups
    networks:
      - crm-network
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request;urllib.request.urlopen(\"http://localhost:8000/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # ========================================
  # FRONTEND (Next.js)
  # ========================================
  frontend:
    build:
      context: ./crm-frontend
      dockerfile: Dockerfile
      target: production
      args:
        # Passer l'URL de l'API au build pour l'inclure dans le bundle Next.js
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://crm.alforis.fr/api/v1}
    restart: always
    depends_on:
      api:
        condition: service_healthy
    env_file:
      - ${COMPOSE_ENV_FILE:-.env.production}
    environment:
      # URL de l'API accessible depuis le navigateur
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://crm.alforis.fr/api/v1}
      NODE_ENV: production
      PORT: ${FRONTEND_PORT:-3010}
    working_dir: /app
    command: npm start
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3010}:${FRONTEND_PORT:-3010}"
    networks:
      - crm-network
    healthcheck:
      # Healthcheck plus robuste qui vérifie vraiment la disponibilité
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://localhost:${FRONTEND_PORT:-3010}\",r=>process.exit(r.statusCode>=200&&r.statusCode<500?0:1)).on(\"error\",()=>process.exit(1))'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
