[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = '''
/(
    \.git
  | \.venv
  | venv
  | temp-venv
  | __pycache__
  | \.mypy_cache
  | \.pytest_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip_glob = ["*.pyc", "__pycache__/*", ".venv/*", "venv/*", "temp-venv/*"]
known_first_party = ["api", "core", "models", "schemas", "services", "routers", "tasks"]
